name: Test Issue Template
description: 이건 잘 떠야 해 제발...!
title: "[Test]"
labels: []

body:
  - type: textarea
    id: what-happened
    attributes:
      label: 무슨 일이 있었나요?
      description: 간단히 서술해주세요
      placeholder: 예: 앱이 크래시났어요
