name: "Pull Request Template"
description: "PR 템플릿입니다."
title: "[] "
body:
  - type: textarea
    id: what-i-did
    attributes:
      label: 🗯️ 작업 내용 (What I did)
      description: 이 PR에서 작업한 내용을 간략히 설명해주세요.
      placeholder: ex. 로그인 페이지 레이아웃 수정
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: 📌 변경 사항 (Changes)
      description: 체크박스를 수정하거나 추가해 주세요.
      placeholder: |
        - [ ] 주요 기능 추가 / 변경
        - [ ] 코드 리팩토링
        - [ ] 버그 수정
        - [ ] 기타 (설명 필요)
  - type: input
    id: related-issue
    attributes:
      label: 📂 관련 이슈 (Issue)
      description: 관련된 이슈 번호를 연결해주세요. (`#이슈번호`)
      placeholder: "#123"
  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ 체크리스트 (Checklist)
      options:
        - label: 코드에 오류가 없는지 확인하셨나요?
        - label: 주요 변경 사항을 문서화하셨나요?
        - label: 단위 테스트 또는 통합 테스트를 추가했나요? (해당하는 경우)
        - label: 리뷰어가 확인해야 할 포인트가 있다면 적어주세요.
  - type: textarea
    id: notes
    attributes:
      label: 💡 추가 설명 (Additional Info)
      description: 리뷰어가 알면 좋은 추가적인 내용을 적어주세요.
      placeholder: ex. 기술적 의사 결정, 고려사항 등
