name: "✅ Test"
description: "새로운 기능 추가"
labels: ["✅ Test"]
title: " [TEST] "
body:
  - type: textarea
    attributes:
      label: 📌 개요
      description: 테스트가 필요한 이유와 주요 목표를 간략히 설명해 주세요.
      placeholder: ex. 신규 기능에 대한 테스트 필요
  - type: textarea
    attributes:
      label: 🎯 테스트 대상
      description: 어떤 기능, 모듈, 컴포넌트를 테스트할 것인지 기재해 주세요.
      placeholder: ex. 로그인 모듈, 유저 컴포넌트 등
  - type: checkboxes
    attributes:
      label: 🔍 테스트 시나리오
      description: 테스트 항목과 기대 결과를 선택해주세요.
      options:
        - label: [기능/컴포넌트] 입력값 A → 결과 B 확인
        - label: [기능/컴포넌트] 경계값 테스트 (최소값/최대값)
        - label: [기능/컴포넌트] 예외 처리 테스트
        - label: [API 테스트] 정상 요청 → 200 OK
        - label: [API 테스트] 잘못된 요청 → 에러 코드 반환
        - label: [UI 테스트] 버튼 클릭 → 올바른 동작 수행
        - label: [UI 테스트] 화면 요소 정상 렌더링
  - type: checkboxes
    attributes:
      label: ✅ 체크리스트
      options:
        - label: 단위 테스트 (Unit Test)
        - label: 통합 테스트 (Integration Test)
        - label: E2E 테스트 (End-to-End Test)
        - label: 성능 테스트 (Performance Test)
        - label: 기타 (추가 테스트 필요 시 기재)
  - type: textarea
    attributes:
      label: 📂 관련 파일 / 테스트 코드 위치
      description: 테스트 코드가 작성될 파일 경로 또는 위치를 명시해 주세요.
      placeholder: ex. /tests/Login.test.tsx
  - type: textarea
    attributes:
      label: 📝 참고 사항
      description: 추가적으로 공유하거나 논의하고 싶은 내용을 작성해 주세요.
